language: cpp
script: "make"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
compiler:
  - clang
  - gcc
branches:
  only:
    - master
notifications:
  email:
    - andrew@andrewschaaf.com
