# language: cpp
# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -y libopencv-dev
# compiler:
#   - clang
#   - gcc

language: objective-c
before_install:
  - brew update
  - brew tap homebrew/science
  - brew install opencv

script: "make"
branches:
  only:
    - master
notifications:
  email:
    - andrew@andrewschaaf.com
